export type HandType = 'left' | 'right';
export type FingerType = 'pinky' | 'ring' | 'middle' | 'index' | 'thumb';

export interface FingerMapping {
  hand: HandType;
  finger: FingerType;
}

export const FINGER_MAP: { [key: string]: FingerMapping } = {
    // Fila superior (números y símbolos principales)
  '1': { hand: 'left', finger: 'pinky' },
  '!': { hand: 'left', finger: 'pinky' },
  '|': { hand: 'left', finger: 'pinky' },
  '2': { hand: 'left', finger: 'ring' },
  '"': { hand: 'left', finger: 'ring' },
  '@': { hand: 'left', finger: 'ring' },
  '3': { hand: 'left', finger: 'middle' },
  '·': { hand: 'left', finger: 'middle' },
  '#': { hand: 'left', finger: 'middle' },
  '4': { hand: 'left', finger: 'index' },
  '$': { hand: 'left', finger: 'index' },
  '~': { hand: 'left', finger: 'index' },
  '5': { hand: 'left', finger: 'index' },
  '%': { hand: 'left', finger: 'index' },
  '€': { hand: 'left', finger: 'index' },
  '6': { hand: 'right', finger: 'index' },
  '&': { hand: 'right', finger: 'index' },
  '¬': { hand: 'right', finger: 'index' },
  '7': { hand: 'right', finger: 'index' },
  '/': { hand: 'right', finger: 'index' },
  '8': { hand: 'right', finger: 'middle' },
  '(': { hand: 'right', finger: 'middle' },
  '9': { hand: 'right', finger: 'ring' },
  ')': { hand: 'right', finger: 'ring' },
  '0': { hand: 'right', finger: 'pinky' },
  '=': { hand: 'right', finger: 'pinky' },
  '?': { hand: 'right', finger: 'pinky' },
  "'": { hand: 'right', finger: 'pinky' },
  '¡': { hand: 'right', finger: 'pinky' },
  '¿': { hand: 'right', finger: 'pinky' },
  '-': { hand: 'right', finger: 'pinky' },
  '_': { hand: 'right', finger: 'pinky' },
  '—': { hand: 'right', finger: 'pinky' },
  'º': { hand: 'left', finger: 'pinky' },
  'ª': { hand: 'left', finger: 'pinky' },
  '\\': { hand: 'left', finger: 'pinky' },

  // Fila QWERTY
  'q': { hand: 'left', finger: 'pinky' },
  'w': { hand: 'left', finger: 'ring' },
  'e': { hand: 'left', finger: 'middle' },
  'r': { hand: 'left', finger: 'index' },
  't': { hand: 'left', finger: 'index' },
  'y': { hand: 'right', finger: 'index' },
  'u': { hand: 'right', finger: 'index' },
  'i': { hand: 'right', finger: 'middle' },
  'o': { hand: 'right', finger: 'ring' },
  'p': { hand: 'right', finger: 'pinky' },
  '`': { hand: 'right', finger: 'pinky' },
  '^': { hand: 'right', finger: 'pinky' },
  '[': { hand: 'right', finger: 'pinky' },
  '+': { hand: 'right', finger: 'pinky' },
  '*': { hand: 'right', finger: 'pinky' },
  ']': { hand: 'right', finger: 'pinky' },

  // Fila ASDF
  'a': { hand: 'left', finger: 'pinky' },
  's': { hand: 'left', finger: 'ring' },
  'd': { hand: 'left', finger: 'middle' },
  'f': { hand: 'left', finger: 'index' },
  'g': { hand: 'left', finger: 'index' },
  'h': { hand: 'right', finger: 'index' },
  'j': { hand: 'right', finger: 'index' },
  'k': { hand: 'right', finger: 'middle' },
  'l': { hand: 'right', finger: 'ring' },
  'ñ': { hand: 'right', finger: 'pinky' },
  '{': { hand: 'right', finger: 'pinky' },
  '}': { hand: 'right', finger: 'pinky' },
  'ç': { hand: 'right', finger: 'pinky' },

  // Vocales acentuadas (same finger as non-accented)
  'á': { hand: 'left', finger: 'pinky' },
  'Á': { hand: 'left', finger: 'pinky' },
  'é': { hand: 'left', finger: 'middle' },
  'É': { hand: 'left', finger: 'middle' },
  'í': { hand: 'right', finger: 'middle' },
  'Í': { hand: 'right', finger: 'middle' },
  'ó': { hand: 'right', finger: 'ring' },
  'Ó': { hand: 'right', finger: 'ring' },
  'ú': { hand: 'right', finger: 'index' },
  'Ú': { hand: 'right', finger: 'index' },

  // Fila ZXCV
  '<': { hand: 'left', finger: 'pinky' },
  '>': { hand: 'left', finger: 'pinky' },
  'z': { hand: 'left', finger: 'pinky' },
  'x': { hand: 'left', finger: 'ring' },
  'c': { hand: 'left', finger: 'middle' },
  'v': { hand: 'left', finger: 'index' },
  'b': { hand: 'left', finger: 'index' },
  'n': { hand: 'right', finger: 'index' },
  'm': { hand: 'right', finger: 'index' },
  ',': { hand: 'right', finger: 'middle' },
  ';': { hand: 'right', finger: 'middle' },
  '.': { hand: 'right', finger: 'ring' },
  ':': { hand: 'right', finger: 'ring' },
  '-_': { hand: 'right', finger: 'pinky' },

  // Espacio y modificadores
  ' ': { hand: 'right', finger: 'thumb' },
  'space': { hand: 'right', finger: 'thumb' },
  'shift': { hand: 'left', finger: 'pinky' },
  'ctrl': { hand: 'left', finger: 'pinky' },
  'alt': { hand: 'left', finger: 'thumb' },
  'altgr': { hand: 'right', finger: 'thumb' },
};
