export enum AppView {
  PRACTICE = 'practice',
  FREE_PRACTICE = 'free-practice',
  SPEED_MODE = 'speed-mode',
  PRECISION_MODE = 'precision-mode',
  ZEN_MODE = 'zen-mode',
  NUMBERS_MODE = 'numbers-mode',
  SYMBOLS_MODE = 'symbols-mode',
  CODE_MODE = 'code-mode',
  DICTATION_MODE = 'dictation-mode',
  CHALLENGE_PLAY = 'challenge-play',
  GAME = 'game',
  RACE_MODE = 'race-mode',
  PRACTICE_ROOM = 'practice-room',
  FRIENDS = 'friends',
  MY_LEVELS = 'my-levels',
  CREATE_LEVEL = 'create-level',
  CREATE = 'create',
  STATISTICS = 'statistics',
  ACHIEVEMENTS = 'achievements',
  LEADERBOARD = 'leaderboard',
  PROFILE = 'profile',
  ADMIN_DASHBOARD = 'admin-dashboard',
  COMMUNITY = 'community',
  PUBLIC_PROFILE = 'public-profile',
  CLASSES = 'classes',
  CHALLENGES = 'challenges',
  LOGIN = 'login',
  LOGOUT = 'logout',
  SETTINGS = 'settings',
}

export enum GameSource {
  LEVELS = 'Levels',
  PLAY_GAME = 'PlayGame',
  CREATE_TEXT = 'CreateText',
  LEVEL_CREATOR = 'LevelCreator',
  FREE_PRACTICE = 'FreePractice',
  SPEED_MODE = 'SpeedMode',
  PRECISION_MODE = 'PrecisionMode',
  ZEN_MODE = 'ZenMode',
  NUMBERS_MODE = 'NumbersMode',
  SYMBOLS_MODE = 'SymbolsMode',
  CODE_MODE = 'CodeMode',
  DICTATION_MODE = 'DictationMode',
  RACE_MODE = 'RaceMode',
  CHALLENGE = 'Challenge',
}

export enum UserRole {
  ADMIN = 'admin',
  TEACHER = 'teacher',
  STUDENT = 'student',
}
